# Create a new user
POST http://localhost:3332/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "345520@notfound.local",
  "dateBirth": "2012-02-22",
  "firstname": "Keks",
  "password": "123456",
  "avatar": "1.jpg",
  "gender": "Мужской",
  "role": "тренер",
  "place": "Удельная",
  "trainingLevel": "новичок",
  "trainingType": ["бокс"],
  "certificate": "images/1.pdf",
  "credits": "some credits",
  "isReadyToTrainPersonally": false
}

###

# Create a new user

POST http://localhost:3332/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user88@notfound.local",
  "dateBirth": "2012-02-22",
  "firstname": "Keks",
  "password": "123456",
  "avatar": "1.jpg",
  "gender": "Мужской",
  "role": "пользователь",
  "place": "Удельная",
  "trainingLevel": "любитель",
  "trainingType": ["бокс"],
  "trainingTime": "10-30 мин",
  "caloriesToDrop": 1700,
  "caloriesToSpendPerDay": 1010,
  "isReadyForTraining": true
}

###
# Create a basic user

POST http://localhost:3332/api/auth/register-basic HTTP/1.1
Content-Type: application/json

{
  "email": "user88184512@notfound.local",
  "dateBirth": "2012-02-22",
  "firstname": "Keks",
  "password": "123456",
  "avatar": "1.jpg",
  "gender": "Мужской",
  "role": "пользователь",
  "place": "Удельная"
}



###

# Get user by ID
GET http://localhost:3332/api/auth/6434421323d0a1df18c0ecdf HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDY0MDFhMzhkMjlkZjYxMGE5Mzc3OWUiLCJlbWFpbCI6ImU3Nzc0ZWVlZWUwOTAwNzgzQGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJmaXJzdG5hbWUiOiLQmtC10LrRgSIsImlhdCI6MTY4NTQ4MDU4OCwiZXhwIjoxNjg1NDgxNDg4fQ.k0hJ20mvx5uJejFiCnfABhk3L33_SAMGHdfzE4B8U8M
###


# Get user by token
POST http://localhost:3332/api/auth/checkAuth HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDY0MDFhMzhkMjlkZjYxMGE5Mzc3OWUiLCJlbWFpbCI6ImU3Nzc0ZWVlZWUwOTAwNzgzQGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJmaXJzdG5hbWUiOiLQmtC10LrRgSIsImlhdCI6MTY4NTIxODgzMywiZXhwIjoxNjg1MjE5NzMzfQ.7n0zgFTQNIAzEJ_0y1jWT48Hu6okgLkD6Nc-FebJjlQ
###

# Login user by email and password
POST http://localhost:3332/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "e7774eeeee0900783@gmail.com",
  "password": "123456"
}

###
# Get new access token

POST http://localhost:3332/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDM0NDIxMzIzZDBhMWRmMThjMGVjZGYiLCJlbWFpbCI6IjM0NTI5QG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ItGC0YDQtdC90LXRgCIsImZpcnN0bmFtZSI6Iktla3MiLCJyZWZyZXNoVG9rZW5JZCI6IjQ0YzAxN2QxLTczZTktNGMwZS05MGI5LWM0NGQyM2FmY2UwZCIsImlhdCI6MTY4NDA1OTMwMCwiZXhwIjoxNjg0NjY0MTAwfQ.z06IkouiPD_jwjbscL2Lo5ae28JDnp2sPs68XC94FOg


###
# Update user (coach typed user)
PATCH http://localhost:3332/api/auth/update/6416d6de4260260ffc743779 HTTP/1.1
Content-Type: application/json

{
  "email": "user18@notfound.local",
  "dateBirth": "2015-02-22",
  "firstname": "ULYA",
  "password": "123456",
  "avatar": "1.jpg",
  "gender": "мужской",
  "role": "тренер",
  "place": "Smoln",
  "trainingLevel": "новичок",
  "trainingType": ["бокс"],
  "certificate": "images/5.pdf",
  "credits": "some credits",
  "isReadyToTrainPersonally": true
}


###
# Update user (trainee typed user)

PATCH http://localhost:3332/api/auth/update/6416df824b8763329b4fd4b3 HTTP/1.1
Content-Type: application/json

{
  "email": "user67@notfound.local",
  "dateBirth": "2012-02-22",
  "firstname": "Keksik",
  "password": "123456",
  "avatar": "1.jpg",
  "gender": "22",
  "role": "пользователь",
  "place": "Удельная",
  "trainingLevel": "любитель",
  "trainingType": ["11"],
  "trainingTime": "10-30 мин",
  "caloriesToDrop": 170000,
  "caloriesToSpendPerDay": 3500,
  "isReadyForTraining": true
}

### Get all users
#

GET http://localhost:3332/api/auth HTTP/1.1
Content-Type: application/json


### Get all users with query parameters
#

GET http://localhost:3332/api/auth?trainingType=бокс&page=3&sortDirection=1 HTTP/1.1
Content-Type: application/json


### Add friend
GET http://localhost:3332/api/auth/addfriend/6432dd529ab9e6caf4b325f9 HTTP/1.1
Authorization: Bearer

### Delete friend

GET http://localhost:3332/api/auth/deletefriend/64319c29f053f274593ebbd9 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDY0MDFhMzhkMjlkZjYxMGE5Mzc3OWUiLCJlbWFpbCI6ImU3Nzc0ZWVlZWUwOTAwNzgzQGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJmaXJzdG5hbWUiOiLQmtC10LrRgSIsImlhdCI6MTY4NTQ4MTI0NywiZXhwIjoxNjg1NDgyMTQ3fQ.2fXFbQARtHqx0KBg4go_gQsSFOuFa9MYyfy4riMBVgI

### Get list of friends with details
GET http://localhost:3332/api/auth/friends/64319c39f053f274593ebbdd HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDY0MDFhMzhkMjlkZjYxMGE5Mzc3OWUiLCJlbWFpbCI6ImU3Nzc0ZWVlZWUwOTAwNzgzQGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJmaXJzdG5hbWUiOiLQmtC10LrRgSIsImlhdCI6MTY4NTQ4MTI0NywiZXhwIjoxNjg1NDgyMTQ3fQ.2fXFbQARtHqx0KBg4go_gQsSFOuFa9MYyfy4riMBVgI


###  Upload  user's avatar
POST http://localhost:3332/api/auth/avatar/646401a38d29df610a93779e HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDY0MDFhMzhkMjlkZjYxMGE5Mzc3OWUiLCJlbWFpbCI6ImU3Nzc0ZWVlZWUwOTAwNzgzQGdtYWlsLmNvbSIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJmaXJzdG5hbWUiOiLQmtC10LrRgSIsImlhdCI6MTY4NjUxMDExMywiZXhwIjoxNjg2NTExMDEzfQ.sCidYporzNYC96Vh0zhoxGR2XDc56vOpxQgluyKQJYU

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar.png"
Content-Type: image/png

< /Users/user/Pictures/avatar.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Upload  PDF certificate

POST http://localhost:3332/api/auth/certificate/6428812aab218eeca1ff7ac9 HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDI4ODEyYWFiMjE4ZWVjYTFmZjdhYzkiLCJlbWFpbCI6IjM0NTBAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTY4MDU1MDgxMCwiZXhwIjoxNjgwNTUxNzEwfQ.MtkD_BvbJcSiF7LcdJctNlgC_GuuOCuHBEenBwaM_iw

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="certificate"; filename="certificate.pdf"
Content-Type: application/pdf

< /Users/user/Pictures/GREEN.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###  Add Gym to Favorite Gyms by  user with role Trainee

POST http://localhost:3332/api/auth/favorites/gym/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDMxOWMzOWYwNTNmMjc0NTkzZWJiZGQiLCJlbWFpbCI6InVzZXI3OUBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJmaXJzdG5hbWUiOiJLZWtzIiwiaWF0IjoxNjgwOTgwNzQ0LCJleHAiOjE2ODA5ODE2NDR9.eaCdPrrD4V9iV3wZhKe2OtXb0w1K1TkyqWqMHSKOlt0


###  Add Gym to Favorite Gyms by  user with role Coach

POST http://localhost:3332/api/auth/favorites/gym/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDMxOWMyOWYwNTNmMjc0NTkzZWJiZDkiLCJlbWFpbCI6IjM0NTJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTY4MDk4NDc3OSwiZXhwIjoxNjgwOTg1Njc5fQ.9Oh_DItwLr9IW0Ao_syfYRcIE4a5tQMn_HoXCyzRyww


### Read  the list of favorite gyms  by user

GET http://localhost:3332/api/auth/favorites/gym HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDMxOWMzOWYwNTNmMjc0NTkzZWJiZGQiLCJlbWFpbCI6InVzZXI3OUBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiLQv9C-0LvRjNC30L7QstCw0YLQtdC70YwiLCJmaXJzdG5hbWUiOiJLZWtzIiwiaWF0IjoxNjgxMDUzNTk3LCJleHAiOjE2ODEwNTQ0OTd9.hP_YiOYdnHwNBEk2xaq1l_KVDkLUOam0XHLEveYsph8

###
# Get avatar by ID
GET http://localhost:3332/api/auth/avatars/W37WaCwhqVii3xBC8xU_o.jpg HTTP/1.1

###
