###
# Create a new training
POST http://localhost:3333/api/trainings HTTP/1.
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDI4ODEyYWFiMjE4ZWVjYTFmZjdhYzkiLCJlbWFpbCI6IjM0NTBAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTY4MDQ1Nzg4MiwiZXhwIjoxNjgwNDU4NzgyfQ.T90-uh6oqpK6ptU40zMW0NWlYM7VcNEbDJYsyGTzsaQ
Content-Type: application/json

{
   "title": "Пе=",
   "backgroundImage": "1.png",
   "trainingLevel": "любитель",
   "trainingType": "бокс",
   "trainingTime": "10-30 мин",
   "price": 2000,
   "calories": 2050,
   "description": "какое-то описание",
   "trainingForGender": "для женщин",
   "video": "1.mov",
   "rating": 3,
   "coachId": "13435235",
   "isSpecialOffer": true
}

###
# Get the list of all trainings of the coach
GET http://localhost:3333/api/trainings HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDE2YzY5ZDdiZTA0ZWFjNTlhOTk4N2MiLCJlbWFpbCI6InVzZXIxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJmaXJzdG5hbWUiOiJLZWtzIiwiaWF0IjoxNjc5OTMzNDg1LCJleHAiOjE2Nzk5MzQzODV9.h87Q5rZn6u7y9yJyl6GAONkZ_75i-5c8X-ajpHxKFUY

###
# Get the list of trainings of the coach with price

GET http://localhost:3333/api/trainings?priceMin=1300&trainingTime=30-50 мин HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDE2YzY5ZDdiZTA0ZWFjNTlhOTk4N2MiLCJlbWFpbCI6InVzZXIxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJmaXJzdG5hbWUiOiJLZWtzIiwiaWF0IjoxNjc5OTMzNDg1LCJleHAiOjE2Nzk5MzQzODV9.h87Q5rZn6u7y9yJyl6GAONkZ_75i-5c8X-ajpHxKFUY


### Update training
PATCH http://localhost:3333/api/trainings/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDE2YzVlYmY3YmZhNDhmNjdhYWMxNGYiLCJlbWFpbCI6InVzZXI5QG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ItGC0YDQtdC90LXRgCIsImZpcnN0bmFtZSI6Iktla3MiLCJpYXQiOjE2Nzk5MzIwMzIsImV4cCI6MTY3OTkzMjkzMn0.dbjXqd8kFUgY3yDkVZhOyDuP-UNkfEfz6nIkpPwgIOA
Content-Type: application/json

{
   "title": "Восьмая тренир",
   "backgroundImage": "1.png",
   "trainingLevel": "любитель",
   "trainingType": "бокс",
   "trainingTime": "10-30 мин",
   "price": 2000,
   "calories": 2050,
   "description": "какое-то описание",
   "trainingForGender": "для женщин",
   "video": "1.mov",
   "rating": 3,
   "coachId": "13435235",
   "isSpecialOffer": true
}

### Get detailed information about training

GET http://localhost:3333/api/trainings/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDE2YzY5ZDdiZTA0ZWFjNTlhOTk4N2MiLCJlbWFpbCI6InVzZXIxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJmaXJzdG5hbWUiOiJLZWtzIiwiaWF0IjoxNjc5OTM0Mzk2LCJleHAiOjE2Nzk5MzUyOTZ9.LiHlP2iEaWYwQUb-0j_lQKdKbdeXUyty-48-soAgasA

###  Load background image for training

POST http://localhost:3333/api/trainings/background_image/3 HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDI4ODEyYWFiMjE4ZWVjYTFmZjdhYzkiLCJlbWFpbCI6IjM0NTBAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTY4MDUzMjM3NiwiZXhwIjoxNjgwNTMzMjc2fQ.tN8hUa52Ki419GgpV7uff5R9WU06AFIdEpYDdQLSej0

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="backgroundImage"; filename="avatar3.png"
Content-Type: image/png

< /Users/user/Pictures/avatar3.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###  Load video  for training

POST http://localhost:3333/api/trainings/video/3 HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDI4ODEyYWFiMjE4ZWVjYTFmZjdhYzkiLCJlbWFpbCI6IjM0NTBAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTY4MDUzNDM0NCwiZXhwIjoxNjgwNTM1MjQ0fQ.fu8ENOYH2IT5XfMFy2hgyEDv5_45dePqmfc5MkhIfg8

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="video"; filename="cover.mp4"
Content-Type: video/mp4

< /Users/user/Pictures/cover.mp4
------WebKitFormBoundary7MA4YWxkTrZu0gW--
