###
# Create a new order
POST http://localhost:3333/api/orders HTTP/1.
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDI4ODEyYWFiMjE4ZWVjYTFmZjdhYzkiLCJlbWFpbCI6IjM0NTBAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoi0YLRgNC10L3QtdGAIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTY4MDQ1Nzg4MiwiZXhwIjoxNjgwNDU4NzgyfQ.T90-uh6oqpK6ptU40zMW0NWlYM7VcNEbDJYsyGTzsaQ
Content-Type: application/json

{
   "orderType": "абонемент",
   "userId": "6416c5ebf7bfa48f67aac14f",
   "trainingId": 1,
   "gymId": 2,
   "price": 100,
   "quantity": 5,
   "paymentWay": "mir"
}

###
# Get the list of all orders of the coach
GET http://localhost:3333/api/orders HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDE2YzVlYmY3YmZhNDhmNjdhYWMxNGYiLCJlbWFpbCI6InVzZXI5QG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ItGC0YDQtdC90LXRgCIsImZpcnN0bmFtZSI6Iktla3MiLCJpYXQiOjE2ODAyOTA1ODUsImV4cCI6MTY4MDI5MTQ4NX0._8DZLgqPsWFTrpss901VHQW2FSPVcjyIWATh-qsxPNM

###
# Get the list of orders  with price

GET http://localhost:3333/api/trainings?priceMin=1300&trainingTime=30-50 мин HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDM0NDIxMzIzZDBhMWRmMThjMGVjZGYiLCJlbWFpbCI6IjM0NTI5QG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ItGC0YDQtdC90LXRgCIsImZpcnN0bmFtZSI6Iktla3MiLCJpYXQiOjE2ODM0ODI2MzIsImV4cCI6MTY4MzQ4MzUzMn0.j7aBEtzSr2TH2dIAlmhWWBJ8wa_oU-n5Ovrs45LWq_8


### Update order
PATCH http://localhost:3333/api/orders/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDE2YzVlYmY3YmZhNDhmNjdhYWMxNGYiLCJlbWFpbCI6InVzZXI5QG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ItGC0YDQtdC90LXRgCIsImZpcnN0bmFtZSI6Iktla3MiLCJpYXQiOjE2ODAyOTEwMTYsImV4cCI6MTY4MDI5MTkxNn0.OoddgWm7BLJXSO12wBC1j_lTLkqAr3UgJ1lXhNFjxy8
Content-Type: application/json

{
   "id": 9,
   "orderType": "тренировка",
   "userId": "6416c5ebf7bfa48f67aac14f",
   "trainingId": 1,
   "gymId": 1,
   "price": 1000,
   "quantity": 2,
   "paymentWay": "umoney"
}

### Get detailed information about order

GET http://localhost:3333/api/orders/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDE2YzVlYmY3YmZhNDhmNjdhYWMxNGYiLCJlbWFpbCI6InVzZXI5QG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ItGC0YDQtdC90LXRgCIsImZpcnN0bmFtZSI6Iktla3MiLCJpYXQiOjE2ODAyOTA2NTIsImV4cCI6MTY4MDI5MTU1Mn0.OumPmKyY6bo1oA8Ovjk5IaveHgnkndo8ZTeE3QOB0hM



