###
# Create a new training
POST http://localhost:3333/api/orders HTTP/1.
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDE2YzVlYmY3YmZhNDhmNjdhYWMxNGYiLCJlbWFpbCI6InVzZXI5QG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ItGC0YDQtdC90LXRgCIsImZpcnN0bmFtZSI6Iktla3MiLCJpYXQiOjE2ODAyODk3ODAsImV4cCI6MTY4MDI5MDY4MH0.CHERAh_oQlLJ_3M_t3tRUU7lvCwq21uD_KFbgwXazIQ
Content-Type: application/json

{
   "orderType": "абонемент",
   "userId": "6416c5ebf7bfa48f67aac14f",
   "trainingId": 1,
   "gymId": 1,
   "price": 100,
   "quantity": 5,
   "paymentWay": "mir"
}

###
# Get the list of all trainings of the coach
GET http://localhost:3333/api/orders HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDE2YzVlYmY3YmZhNDhmNjdhYWMxNGYiLCJlbWFpbCI6InVzZXI5QG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ItGC0YDQtdC90LXRgCIsImZpcnN0bmFtZSI6Iktla3MiLCJpYXQiOjE2ODAyOTA1ODUsImV4cCI6MTY4MDI5MTQ4NX0._8DZLgqPsWFTrpss901VHQW2FSPVcjyIWATh-qsxPNM

###
# Get the list of trainings of the coach with price

GET http://localhost:3333/api/trainings?priceMin=1300&trainingTime=30-50 мин HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDE2YzY5ZDdiZTA0ZWFjNTlhOTk4N2MiLCJlbWFpbCI6InVzZXIxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiLRgtGA0LXQvdC10YAiLCJmaXJzdG5hbWUiOiJLZWtzIiwiaWF0IjoxNjc5OTMzNDg1LCJleHAiOjE2Nzk5MzQzODV9.h87Q5rZn6u7y9yJyl6GAONkZ_75i-5c8X-ajpHxKFUY


### Update training
PATCH http://localhost:3333/api/orders/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDE2YzVlYmY3YmZhNDhmNjdhYWMxNGYiLCJlbWFpbCI6InVzZXI5QG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ItGC0YDQtdC90LXRgCIsImZpcnN0bmFtZSI6Iktla3MiLCJpYXQiOjE2ODAyOTEwMTYsImV4cCI6MTY4MDI5MTkxNn0.OoddgWm7BLJXSO12wBC1j_lTLkqAr3UgJ1lXhNFjxy8
Content-Type: application/json

{
   "id": 9,
   "orderType": "тренировка",
   "userId": "6416c5ebf7bfa48f67aac14f",
   "trainingId": 1,
   "gymId": 1,
   "price": 1000,
   "quantity": 2,
   "paymentWay": "umoney"
}

### Get detailed information about training

GET http://localhost:3333/api/orders/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDE2YzVlYmY3YmZhNDhmNjdhYWMxNGYiLCJlbWFpbCI6InVzZXI5QG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ItGC0YDQtdC90LXRgCIsImZpcnN0bmFtZSI6Iktla3MiLCJpYXQiOjE2ODAyOTA2NTIsImV4cCI6MTY4MDI5MTU1Mn0.OumPmKyY6bo1oA8Ovjk5IaveHgnkndo8ZTeE3QOB0hM



